"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Plus, Minus } from "lucide-react"

const FAQS = [
  {
    q: "How accurate are the scores?",
    a: "Scores are generated by Perplexity's sonar-pro model with live web search. Each score is broken into sub-components with calibration anchors (e.g. a todo app scores a 3 on demand, Stripe in 2010 scores an 8) to keep results grounded. No AI score is perfect, but the goal is a structured, researched starting point — not a magic number.",
  },
  {
    q: "Is my idea kept private?",
    a: "Yes. Your idea is sent to Perplexity's API solely to generate the report and is not stored on our servers. We never use your inputs to train models. Each session is isolated and the report lives in your browser's local storage only.",
  },
  {
    q: "How is this different from just asking ChatGPT?",
    a: "Verdict uses live web search to pull real competitor data, recent funding rounds, current market sizes, and actual company failures — not just training data from months ago. It also forces a structured framework (clarity, entry, viability) with calibrated scoring instead of a freeform answer.",
  },
  {
    q: "How long does a validation take?",
    a: "About 30–60 seconds. Six parallel research calls run simultaneously so you get a full report — market size, competitors, entry barriers, go/no-go verdict, and devil's advocate — in under a minute.",
  },
  {
    q: "Can I re-validate with updated context?",
    a: "Yes. On any report page there's a Re-validate button that reruns only the founder-specific sections (entry score and verdict) using your founder profile, while keeping the market and competitor research from the original run to save cost.",
  },
  {
    q: "What's included in the free plan?",
    a: "The free Starter plan gives you 3 validations per month with competitor overview, market sizing, and the go/no-go verdict. Paid plans unlock more validations, PDF export, saved reports, and the devil's advocate failure analysis.",
  },
]

function FAQItem({ q, a, index }: { q: string; a: string; index: number }) {
  const [open, setOpen] = useState(false)

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.3 }}
      transition={{ duration: 0.4, delay: index * 0.05, ease: [0.22, 1, 0.36, 1] }}
      className="border-b"
      style={{ borderColor: "#2A2D35" }}
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 py-5 text-left"
      >
        <span className="text-base font-medium text-white">{q}</span>
        <span
          className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center transition-colors"
          style={{ background: open ? "#10B981" : "#1C1F26", color: open ? "#fff" : "#6B7280" }}
        >
          {open ? <Minus size={13} /> : <Plus size={13} />}
        </span>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="answer"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <p className="pb-5 text-sm leading-relaxed" style={{ color: "#9CA3AF" }}>
              {a}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

export function FAQSection() {
  return (
    <section className="bg-[#000000] px-4 py-20 [font-family:var(--font-inter),system-ui,sans-serif]">
      <div className="mx-auto max-w-2xl">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
          className="mb-12 text-center"
        >
          <h2 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">Frequently asked questions</h2>
          <p className="mt-3 text-base" style={{ color: "#6B7280" }}>Everything you need to know before you validate.</p>
        </motion.div>

        <div>
          {FAQS.map((item, i) => (
            <FAQItem key={i} q={item.q} a={item.a} index={i} />
          ))}
        </div>
      </div>
    </section>
  )
}
